const h2 = document.createElement("h2");
h2.textContent = "Here is a list generated by JavaScript";
document.querySelector("body").appendChild(h2);

const div = document.createElement("div");
document.body.append(div);

const ul = document.createElement("ul");
for (let i = 0; i < 3; i++) {
    const li = document.createElement("li");
    li.textContent = (i + 1).toString();
    ul.append(li);
}

div.append(ul);

