const h2 = document.createElement("h2");
h2.textContent = "Here is a list generated by JavaScript";
document.querySelector("body").appendChild(h2);

const div = document.createElement("div");
document.body.append(div);

const ul = document.createElement("ul");
for (let i = 0; i < 3; i++) {
    const li = document.createElement("li");
    li.textContent = (i + 1).toString();
    ul.append(li);
}

div.append(ul);

const mainTitle = document.getElementById("Main-Title");

mainTitle.style.color = "black";

mainTitle.addEventListener("click", function (event) {
    console.log(mainTitle.style.color)
    if (mainTitle.style.color === "white") {
        mainTitle.style.color = "black";
    } else {
        mainTitle.style.color = "white";
    }
});

// mainTitle.addEventListener("click", function (event) {
//     console.log(event);
//     if (event.altKey === true) {
//         mainTitle.style.color = "white";
//     }
// });